# The west manifest file for the nRF Connect SDK (NCS).
#
# The per-installation west configuration file specifies the location of this
# manifest file. The "path" option in the [manifest] section of .west/config
# defines the folder that contains west.yml. The path is relative to the folder
# that contains .west.
#
# You can create your own manifest files and put them in any
# repository you want, to create your own custom NCS installation.
# For example, you could create a manifest file in your own
# out-of-tree application directory, which would pull the nrf repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new NCS installation. See the west documentation for more
# information.

west:
  url: https://github.com/zephyrproject-rtos/west
  revision: master

manifest:
  defaults:
    remote: ncs

  remotes:
      # nRF Connect SDK base URL.
    - name: ncs
      url-base: https://github.com/NordicPlayground
    - name: jtguggedal
      url-base: https://github.com/jtguggedal
    - name: joakimtoe
      url-base: https://github.com/joakimtoe

  # The list of external projects for the nRF Connect SDK.
  #
  projects:
    - name: fw-nrfconnect-zephyr
      path: zephyr
      west-commands: scripts/west-commands.yml
      revision: 50e037e0e2fd00d29f8b37e50b352c10f9ee8b62
      remote: jtguggedal
    - name: fw-nrfconnect-mcuboot
      path: mcuboot
      revision: 59fcf18dba985cd23b35d48843b9379d5466030f
      remote: joakimtoe
    - name: nrfxlib
      path: nrfxlib
      revision: c725827ce7bb5c9f038efcf86979b13c87292bb4
      remote: jtguggedal

  self:
    path: nrf
